### PR TITLE
Projects setup

### PR DESCRIPTION
**Pull request by SirriRyisa**
## Hello Reviewer, 

**On this milestone we have done:** 

- [ ] 1. Created the Kanban-board as per the project's requirement
- [ ] 2. Created work environment for the project
- [ ] 3. Link to the Kanban-board: https://github.com/users/SirriRyisa/projects/2
- [ ] 4. We are two on this project: https://github.com/SirriRyisa and https://github.com/sangwa7
- [ ] 5. Group members: @sangwa7  and @SirriRyisa

### CODE REVIEW

**Comment by Lordkaito** [comment]
Hi @SirriRyisa, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [ ] Please make sure to add a link to the kanban board for your project, as this is part of the requirements and I can't proceed with the review if it is not present. I realized you have the issues created, but the link to the kanban board is required. 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by elmar8287** [comment]
## STATUS: INVALID

Hi, team.

I have to mark your submission invalid because you forgot to mention the following requirement:

- information about the number of people in the group

Please, try to fix it and submit it again.

Happy coding! 👍

**Comment by t-yanick** [comment]
Hi Team, 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good job with tasks distribution. 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sangwa7** [comment]
> ## STATUS: INVALID
> Hi, team.
> 
> I have to mark your submission invalid because you forgot to mention the following requirement:
> 
> * information about the number of people in the group
> 
> Please, try to fix it and submit it again.
> 
> Happy coding! 👍

Hello @elmar8287 

Thank you for a thorough review provided.

We have been able to make changes that required however on the dashboard you haven't marked it as

**Pull request closed without merging**
